# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Bikeshed
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coworking space in Nashville, Tennessee.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thebikeshed.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  websages
webcams_url: "https://puppycam.thebikeshed.io/"

# Build settings
markdown: kramdown

exclude: ["Gemfile", "deploy.sh", "README.md", "Gemfile.lock", ".gitignore"]

# See http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/index.html
